### ISSUE TITLE
Please Add Null-Safety

### ISSUE THREAD

**Issue by capemsx** [Vungle/Flutter-Plugin#11]
Hello,
on **Vungle 0.6.9+4** Null-Safety isn't integrated, so please add support.

Best regards!

**Comment by hortigado** [comment]
please

**Comment by elkhalifte** [comment]
add this one inside your pubspec.yaml
i have added null safety into it

```
vungle:
    git:
     url: https://github.com/elkhalifte/Flutter-Plugin.git
```

Good Luck.

**Comment by Neo490** [comment]
> add this one inside your pubspec.yaml i have added null safety into it
> 
> ```
> vungle:
>     git:
>      url: https://github.com/elkhalifte/Flutter-Plugin.git
> ```
> 
> Good Luck.

Hi, I used the version you provided, but I'm having an issue when trying to run/build the app:
`/D:/Flutter/flutter/.pub-cache/git/Flutter-Plugin-6edded17b1a1ae7675f79da701062c7fdfa6b018/lib/vungle.dart:57:21: Error: A value of type 'Future<dynamic>' can't be returned from an async function with return type 'Future<String>'.
 - 'Future' is from 'dart:async'.
    return _channel.invokeMethod('sdkVersion');
                    ^
/D:/Flutter/flutter/.pub-cache/git/Flutter-Plugin-6edded17b1a1ae7675f79da701062c7fdfa6b018/lib/vungle.dart:183:12: Warning: Operand of null-aware operation '!' has type 'Map<String, UserConsentStatus>' which excludes null.
 - 'Map' is from 'dart:core'.
 - 'UserConsentStatus' is from 'package:vungle/vungle.dart' ('/D:/Flutter/flutter/.pub-cache/git/Flutter-Plugin-6edded17b1a1ae7675f79da701062c7fdfa6b018/lib/vungle.dart').
    return _statusStringToUserConsentStatus![status];
           ^


FAILURE: Build failed with an exception.

* Where:
Script 'D:\Flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1070

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\Flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1`

I'm getting the "official?" version for a while. Hope we could get this working :)
